//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.17.0
//     from Assets/Paddle.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Paddle.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Paddle: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Paddle()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Paddle"",
    ""maps"": [
        {
            ""name"": ""paddles"",
            ""id"": ""cd14f4ff-3084-4610-ba55-a835dc58cebe"",
            ""actions"": [
                {
                    ""name"": ""p1Up"",
                    ""type"": ""Button"",
                    ""id"": ""e77bb5d9-7a2b-4c8b-b538-3702c1a13125"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""p1Down"",
                    ""type"": ""Button"",
                    ""id"": ""9f236118-9317-4779-8f5c-3694a962abc5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""p2Up"",
                    ""type"": ""Button"",
                    ""id"": ""8ce803cb-c1f3-4764-ae23-50c19f727b48"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""p2Down"",
                    ""type"": ""Button"",
                    ""id"": ""7728c240-c35e-4b3f-8522-35f289aedf9f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f4edee05-bfe2-4de9-8942-7ad18b57371b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee232b1c-f8e5-47c2-bb34-083f423bbab6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p1Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""158880ca-1535-4efe-9096-de233f6ad69b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p2Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27d0b9d0-4a52-46a6-8237-599636add98d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""p2Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New Control Scheme"",
            ""bindingGroup"": ""New Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // paddles
        m_paddles = asset.FindActionMap("paddles", throwIfNotFound: true);
        m_paddles_p1Up = m_paddles.FindAction("p1Up", throwIfNotFound: true);
        m_paddles_p1Down = m_paddles.FindAction("p1Down", throwIfNotFound: true);
        m_paddles_p2Up = m_paddles.FindAction("p2Up", throwIfNotFound: true);
        m_paddles_p2Down = m_paddles.FindAction("p2Down", throwIfNotFound: true);
    }

    ~@Paddle()
    {
        UnityEngine.Debug.Assert(!m_paddles.enabled, "This will cause a leak and performance issues, Paddle.paddles.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // paddles
    private readonly InputActionMap m_paddles;
    private List<IPaddlesActions> m_PaddlesActionsCallbackInterfaces = new List<IPaddlesActions>();
    private readonly InputAction m_paddles_p1Up;
    private readonly InputAction m_paddles_p1Down;
    private readonly InputAction m_paddles_p2Up;
    private readonly InputAction m_paddles_p2Down;
    /// <summary>
    /// Provides access to input actions defined in input action map "paddles".
    /// </summary>
    public struct PaddlesActions
    {
        private @Paddle m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PaddlesActions(@Paddle wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "paddles/p1Up".
        /// </summary>
        public InputAction @p1Up => m_Wrapper.m_paddles_p1Up;
        /// <summary>
        /// Provides access to the underlying input action "paddles/p1Down".
        /// </summary>
        public InputAction @p1Down => m_Wrapper.m_paddles_p1Down;
        /// <summary>
        /// Provides access to the underlying input action "paddles/p2Up".
        /// </summary>
        public InputAction @p2Up => m_Wrapper.m_paddles_p2Up;
        /// <summary>
        /// Provides access to the underlying input action "paddles/p2Down".
        /// </summary>
        public InputAction @p2Down => m_Wrapper.m_paddles_p2Down;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_paddles; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PaddlesActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PaddlesActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PaddlesActions" />
        public void AddCallbacks(IPaddlesActions instance)
        {
            if (instance == null || m_Wrapper.m_PaddlesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PaddlesActionsCallbackInterfaces.Add(instance);
            @p1Up.started += instance.OnP1Up;
            @p1Up.performed += instance.OnP1Up;
            @p1Up.canceled += instance.OnP1Up;
            @p1Down.started += instance.OnP1Down;
            @p1Down.performed += instance.OnP1Down;
            @p1Down.canceled += instance.OnP1Down;
            @p2Up.started += instance.OnP2Up;
            @p2Up.performed += instance.OnP2Up;
            @p2Up.canceled += instance.OnP2Up;
            @p2Down.started += instance.OnP2Down;
            @p2Down.performed += instance.OnP2Down;
            @p2Down.canceled += instance.OnP2Down;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PaddlesActions" />
        private void UnregisterCallbacks(IPaddlesActions instance)
        {
            @p1Up.started -= instance.OnP1Up;
            @p1Up.performed -= instance.OnP1Up;
            @p1Up.canceled -= instance.OnP1Up;
            @p1Down.started -= instance.OnP1Down;
            @p1Down.performed -= instance.OnP1Down;
            @p1Down.canceled -= instance.OnP1Down;
            @p2Up.started -= instance.OnP2Up;
            @p2Up.performed -= instance.OnP2Up;
            @p2Up.canceled -= instance.OnP2Up;
            @p2Down.started -= instance.OnP2Down;
            @p2Down.performed -= instance.OnP2Down;
            @p2Down.canceled -= instance.OnP2Down;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PaddlesActions.UnregisterCallbacks(IPaddlesActions)" />.
        /// </summary>
        /// <seealso cref="PaddlesActions.UnregisterCallbacks(IPaddlesActions)" />
        public void RemoveCallbacks(IPaddlesActions instance)
        {
            if (m_Wrapper.m_PaddlesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PaddlesActions.AddCallbacks(IPaddlesActions)" />
        /// <seealso cref="PaddlesActions.RemoveCallbacks(IPaddlesActions)" />
        /// <seealso cref="PaddlesActions.UnregisterCallbacks(IPaddlesActions)" />
        public void SetCallbacks(IPaddlesActions instance)
        {
            foreach (var item in m_Wrapper.m_PaddlesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PaddlesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PaddlesActions" /> instance referencing this action map.
    /// </summary>
    public PaddlesActions @paddles => new PaddlesActions(this);
    private int m_NewControlSchemeSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme NewControlSchemeScheme
    {
        get
        {
            if (m_NewControlSchemeSchemeIndex == -1) m_NewControlSchemeSchemeIndex = asset.FindControlSchemeIndex("New Control Scheme");
            return asset.controlSchemes[m_NewControlSchemeSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "paddles" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PaddlesActions.AddCallbacks(IPaddlesActions)" />
    /// <seealso cref="PaddlesActions.RemoveCallbacks(IPaddlesActions)" />
    public interface IPaddlesActions
    {
        /// <summary>
        /// Method invoked when associated input action "p1Up" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Up(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "p1Down" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Down(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "p2Up" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Up(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "p2Down" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Down(InputAction.CallbackContext context);
    }
}
